version: 2
updates:
  # Maven 依赖更新
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    groups:
      test-dependencies:
        patterns:
          - "org.junit.*"
          - "org.mockito*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      action-dependencies:
        patterns:
          - "actions/checkout"
          - "actions/setup-node"
        update-types:
          - "minor"
          - "patch"